### ISSUE TITLE
Password with '@' character breaks the link

### ISSUE THREAD

**Issue by janhuntjens** [babobski/Open-In-FileZilla#1]
Hey there,

I've found your plugin just now, this is EXACTLY what I missed from my switch from Coda and Mac OSX to Windows and Komodo Edit. So for what it's worth: Thank you very much!

Now I'm still having a little problem, when there is a password containing a '@' character, the link breaks. Is there an easy fix for this? I image you could either escape invalid character or wrap the password, but I'm not sure how it works myself.

Are you maintaining this plug-in and would you be open to fixing this?

**Comment by babobski** [comment]
@janhuntjens thanks for the appreciation.

I will look in to this, as it should work with any password.
Will report back when the issue is fixed.

**Comment by babobski** [comment]
@janhuntjens added a fix for it in the [latest release](https://github.com/babobski/Open-In-FileZilla/releases/tag/1.1-beta), can you test if this works out for you?
Escaped the password by double quoting it, tested it with my own server but I don't have a @ in my password. It still connects to my server but fails to connect because my password is incorrect.

So I think this should fix it, but can you confirm the fix?

**Comment by janhuntjens** [comment]
@babobski Thanks Bob! It works great now.

**Comment by babobski** [comment]
@janhuntjens Thanks great to hear 👍
